Tweets Classification Project

In [ ]:
# classifying tweets into two classes disaster or not disaster

Get The dataSet

We need text dataset to model it

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

chemin = "/content/drive/MyDrive/Nlp With Disaster/"

train = pd.read_csv(chemin + "train_data_cleaning.csv")
test = pd.read_csv(chemin + "test_data_cleaning.csv")

print(train.head())

Mounted at /content/drive
   id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this  # earthquake...
1   4     NaN      NaN           Forest fire near La Ronge Sask .  Canada
2   5     NaN      NaN  All residents asked to  ' shelter in place '  ...
3   6     NaN      NaN  13,000 people receive  # wildfires evacuation ...
4   7     NaN      NaN  Just got sent this photo from Ruby  # Alaska a...

   target
0       1
1       1
2       1
3       1
4       1

In [ ]:
## Becoming one with the data

# Exploratry Data Analysis

# data UnderStanding

In [ ]:
train

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this # earthquake...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask . Canada,1
2,5,NaN,NaN,All residents asked to ' shelter in place ' ...,1
3,6,NaN,NaN,"13,000 people receive # wildfires evacuation ...",1
4,7,NaN,NaN,Just got sent this photo from Ruby # Alaska a...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@ Aria Ahrary @ TheTawniest The out of contr...,1
7610,10871,NaN,NaN,M1 . 94 [ 01 : 04 UTC ] ? 5km S of Volcano H...,1
7611,10872,NaN,NaN,Police investigating after an e - bike collide...,1
7612,10873,NaN,NaN,The Latest : More Homes Razed by Northern Cal...,1

In [ ]:
train.columns

Index(['id', 'keyword', 'location', 'text', 'target'], dtype='object')

In [ ]:
train.describe(include="all")

,id,keyword,location,text,target
count,7613.000000,7552,5080,7613,7613.00000
unique,NaN,221,3341,6981,NaN
top,NaN,fatalities,USA,Watch This Airport Get Swallowed Up By A Sands...,NaN
freq,NaN,45,104,24,NaN
mean,5441.934848,NaN,NaN,NaN,0.42966
std,3137.116090,NaN,NaN,NaN,0.49506
min,1.000000,NaN,NaN,NaN,0.00000
25%,2734.000000,NaN,NaN,NaN,0.00000
50%,5408.000000,NaN,NaN,NaN,0.00000
75%,8146.000000,NaN,NaN,NaN,1.00000
max,10873.000000,NaN,NaN,NaN,1.00000

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

In [ ]:
train.tail()

,id,keyword,location,text,target
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@ Aria Ahrary @ TheTawniest The out of contr...,1
7610,10871,NaN,NaN,M1 . 94 [ 01 : 04 UTC ] ? 5km S of Volcano H...,1
7611,10872,NaN,NaN,Police investigating after an e - bike collide...,1
7612,10873,NaN,NaN,The Latest : More Homes Razed by Northern Cal...,1

In [ ]:
train["text"]

0       Our Deeds are the Reason of this  # earthquake...
1                Forest fire near La Ronge Sask .  Canada
2       All residents asked to  ' shelter in place '  ...
3       13,000 people receive  # wildfires evacuation ...
4       Just got sent this photo from Ruby  # Alaska a...
                              ...
7608    Two giant cranes holding a bridge collapse int...
7609     @ Aria Ahrary  @ TheTawniest The out of contr...
7610    M1 . 94  [ 01 : 04 UTC ]  ? 5km S of Volcano H...
7611    Police investigating after an e - bike collide...
7612    The Latest :  More Homes Razed by Northern Cal...
Name: text, Length: 7613, dtype: object

In [ ]:
train["text"][0]

'Our Deeds are the Reason of this  # earthquake May ALLAH Forgive us all'

In [2]:
#shuffle training dataframe

train_df_shuffled = train.sample(frac=1,random_state=42)
train_df_shuffled.head(5)

,id,keyword,location,text,target
2644,3796,destruction,NaN,So you have a new weapon that can cause un - i...,1
2227,3185,deluge,NaN,The f $ & @ ing things I do for # GISHWHES ...,0
5448,7769,police,UK,DT @ georgegalloway : RT @ Galloway4Mayor :...,1
132,191,aftershock,NaN,Aftershock back to school kick off was great ....,0
6845,9810,trauma,"Montgomery County, MD",in response to trauma Children of Addicts deve...,0

In [ ]:
test

,id,keyword,location,text
0,0,NaN,NaN,Just happened a terrible car crash
1,2,NaN,NaN,"Heard about # earthquake is different cities,..."
2,3,NaN,NaN,"there is a forest fire at spot pond, geese are..."
3,9,NaN,NaN,Apocalypse lighting . # Spokane # wildfires
4,11,NaN,NaN,Typhoon Soudelor kills 28 in China and Taiwan
...,...,...,...,...
3258,10861,NaN,NaN,EARTHQUAKE SAFETY LOS ANGELES SAFETY FASTENER...
3259,10865,NaN,NaN,Storm in RI worse than last hurricane . My ci...
3260,10868,NaN,NaN,Green Line derailment in Chicago
3261,10874,NaN,NaN,MEG issues Hazardous Weather Outlook ( HWO )
3262,10875,NaN,NaN,# City of Calgary has activated its Municipal...

In [ ]:
train.target

0       1
1       1
2       1
3       1
4       1
       ..
7608    1
7609    1
7610    1
7611    1
7612    1
Name: target, Length: 7613, dtype: int64

In [ ]:
# How many training examples (training Samples) of each class
train.target.value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [ ]:
# Now our datasets is balanced

In [ ]:
# how many total training samples
len(train)

7613

In [ ]:
# how many total testing samples
len(test)

3263

In [ ]:
train_df_shuffled[["text","target"]]

                                                   text  target
2644  So you have a new weapon that can cause un - i...       1
2227  The f $  &  @ ing things I do for  # GISHWHES ...       0
5448  DT  @ georgegalloway :  RT  @ Galloway4Mayor :...       1
132   Aftershock back to school kick off was great ....       0
6845  in response to trauma Children of Addicts deve...       0
...                                                 ...     ...
5226   @ Eganator2000 There are not many Obliteratio...       0
5390  just had a panic attack bc I do not have enoug...       0
860   Omron HEM - 712C Automatic Blood Pressure Moni...       0
7603  Officials say a quarantine is in place at an A...       1
7270  I moved to England five years ago today .  Wha...       1

[7613 rows x 2 columns]

In [ ]:
train_df_shuffled[["text","target"]][:5]

                                                   text  target
2644  So you have a new weapon that can cause un - i...       1
2227  The f $  &  @ ing things I do for  # GISHWHES ...       0
5448  DT  @ georgegalloway :  RT  @ Galloway4Mayor :...       1
132   Aftershock back to school kick off was great ....       0
6845  in response to trauma Children of Addicts deve...       0

In [3]:
import random

random_index = random.randint(0,len(train)- 5)
for row in train_df_shuffled[["text","target"]][random_index:random_index + 5 ].itertuples():
  _, text, target = row
  print(f"target: {target}","(real Disaster)" if target > 0 else "(not Real Disaster)")
  print(f"text : \n{text}\n")
  print("-----\n")

target: 1 (real Disaster)
text :
I just watched emmerdale nd I do not know who most of them are but a slightly attractive man named Ross just got beat up nd now he is dead

-----

target: 0 (not Real Disaster)
text :
My parents do not believe in the dream .  Sad .

-----

target: 0 (not Real Disaster)
text :
Public Hearing on 2015 - 16  @ SUNY_Orange budget Thurs 8 / 6 at 3 : 15 Emergency Services Ctr Goshen .

-----

target: 1 (real Disaster)
text :
beforeitsnews  :  A sinkhole grows in Brooklyn :  six - meter crater swallows street   )

-----

target: 0 (not Real Disaster)
text :
Blaze is my bro

-----

Split data into training and validation sets

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
train_sentences, val_sentences , train_labels, val_labels = train_test_split(train_df_shuffled["text"].to_numpy(),
                                                                             train_df_shuffled["target"].to_numpy(),
                                                                             test_size=0.1,random_state=42) #Specify the test_Size

In [ ]:
len(train_sentences)

6851

In [ ]:
len(val_sentences)

762

In [ ]:
train_labels[:10]

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 1])

In [ ]:
val_labels[:10]

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [6]:
#check the first 10 samples

train_sentences[:10],train_labels[:10]

(array([' @ mogacola  @ zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        ' @ Gurmeetramrahim  # MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai . ',
        ' @ shakjn  @ C7  @ Magnums im shaking in fear he is gonna hack the planet',
        'Somehow find you and I collide ',
        ' @ EvaHanderek  @ MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing  # Gunsense ',
        ' @ wfaaweather Pete when will the heat wave pass ?  Is it really going to be mid month ?  Frisco Boy Scouts have a canoe trip in Okla . ',
        'Patient - reported outcomes in long - term survivors of metastatic colorectal cancer  -  British Journal of Surgery '],
       dtype=object),
 array([0, 0, 1, 0, 0, 1, 1, 0, 1, 1]))

**Converting text into numbers**

when dealing with a text problem, one of the first things you'll have to do before you can build a model is to convert text to numbers

There are a few ways to do this namely:

   .Tokenization: direct mapping of token(a token could be a word or a character) to number
   
   . Embedding: Create a matrix of feature vector(The Size of the feature vector can be defined and this embedding can be learned).

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

In [8]:
"Data Science and Artificel Intelligence ".split()

['Data', 'Science', 'and', 'Artificel', 'Intelligence']

In [ ]:
len("Data Science and Artificel Intelligence ".split())

5

In [9]:
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

17

In [10]:
max_vocab_length =10000
max_length=15
text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [11]:
#Fit (adapt) the text vectorizer to the training sentences
text_vectorizer.adapt(train_sentences)

In [12]:
my_text = "There is a flood in my street "
text_vectorizer([my_text])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[ 66,   9,   3, 235,   4,  14, 732,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [13]:
import numpy as np
word_in_vocab = text_vectorizer.get_vocabulary()
word_in_vocab

['',
 '[UNK]',
 np.str_('the'),
 np.str_('a'),
 np.str_('in'),
 np.str_('to'),
 np.str_('of'),
 np.str_('i'),
 np.str_('and'),
 np.str_('is'),
 np.str_('you'),
 np.str_('for'),
 np.str_('on'),
 np.str_('it'),
 np.str_('my'),
 np.str_('not'),
 np.str_('with'),
 np.str_('that'),
 np.str_('are'),
 np.str_('at'),
 np.str_('by'),
 np.str_('s'),
 np.str_('this'),
 np.str_('have'),
 np.str_('be'),
 np.str_('from'),
 np.str_('was'),
 np.str_('am'),
 np.str_('like'),
 np.str_('do'),
 np.str_('up'),
 np.str_('will'),
 np.str_('as'),
 np.str_('just'),
 np.str_('me'),
 np.str_('so'),
 np.str_('but'),
 np.str_('we'),
 np.str_('your'),
 np.str_('no'),
 np.str_('out'),
 np.str_('fire'),
 np.str_('has'),
 np.str_('all'),
 np.str_('an'),
 np.str_('when'),
 np.str_('after'),
 np.str_('he'),
 np.str_('news'),
 np.str_('if'),
 np.str_('now'),
 np.str_('via'),
 np.str_('what'),
 np.str_('they'),
 np.str_('new'),
 np.str_('more'),
 np.str_('2'),
 np.str_('or'),
 np.str_('get'),
 np.str_('people'),
 np.str_('about'),
 np.str_('one'),
 np.str_('over'),
 np.str_('who'),
 np.str_('been'),
 np.str_('how'),
 np.str_('there'),
 np.str_('would'),
 np.str_('into'),
 np.str_('can'),
 np.str_('video'),
 np.str_('disaster'),
 np.str_('emergency'),
 np.str_('us'),
 np.str_('police'),
 np.str_('storm'),
 np.str_('than'),
 np.str_('were'),
 np.str_('his'),
 np.str_('time'),
 np.str_('u'),
 np.str_('body'),
 np.str_('her'),
 np.str_('still'),
 np.str_('off'),
 np.str_('some'),
 np.str_('california'),
 np.str_('year'),
 np.str_('suicide'),
 np.str_('man'),
 np.str_('crash'),
 np.str_('burning'),
 np.str_('3'),
 np.str_('malaysia'),
 np.str_('why'),
 np.str_('day'),
 np.str_('back'),
 np.str_('them'),
 np.str_('rt'),
 np.str_('had'),
 np.str_('first'),
 np.str_('buildings'),
 np.str_('love'),
 np.str_('2015'),
 np.str_('1'),
 np.str_('see'),
 np.str_('nuclear'),
 np.str_('got'),
 np.str_('our'),
 np.str_('going'),
 np.str_('did'),
 np.str_('attack'),
 np.str_('world'),
 np.str_('know'),
 np.str_('go'),
 np.str_('cannot'),
 np.str_('bomb'),
 np.str_('today'),
 np.str_('killed'),
 np.str_('fires'),
 np.str_('two'),
 np.str_('dead'),
 np.str_('4'),
 np.str_('hiroshima'),
 np.str_('youtube'),
 np.str_('5'),
 np.str_('old'),
 np.str_('war'),
 np.str_('life'),
 np.str_('let'),
 np.str_('here'),
 np.str_('full'),
 np.str_('families'),
 np.str_('could'),
 np.str_('car'),
 np.str_('train'),
 np.str_('being'),
 np.str_('only'),
 np.str_('many'),
 np.str_('accident'),
 np.str_('think'),
 np.str_('its'),
 np.str_('flight'),
 np.str_('say'),
 np.str_('down'),
 np.str_('their'),
 np.str_('may'),
 np.str_('good'),
 np.str_('watch'),
 np.str_('want'),
 np.str_('airlines'),
 np.str_('she'),
 np.str_('make'),
 np.str_('last'),
 np.str_('way'),
 np.str_('then'),
 np.str_('should'),
 np.str_('help'),
 np.str_('years'),
 np.str_('weather'),
 np.str_('best'),
 np.str_('home'),
 np.str_('wildfire'),
 np.str_('death'),
 np.str_('too'),
 np.str_('city'),
 np.str_('black'),
 np.str_('mass'),
 np.str_('even'),
 np.str_('bombing'),
 np.str_('370'),
 np.str_('because'),
 np.str_('collapse'),
 np.str_('another'),
 np.str_('take'),
 np.str_('pm'),
 np.str_('please'),
 np.str_('him'),
 np.str_('fatal'),
 np.str_('army'),
 np.str_('those'),
 np.str_('need'),
 np.str_('ass'),
 np.str_('work'),
 np.str_('really'),
 np.str_('lol'),
 np.str_('hot'),
 np.str_('right'),
 np.str_('look'),
 np.str_('live'),
 np.str_('water'),
 np.str_('god'),
 np.str_('read'),
 np.str_('legionnaires'),
 np.str_('does'),
 np.str_('school'),
 np.str_('reddit'),
 np.str_('forest'),
 np.str_('9'),
 np.str_('northern'),
 np.str_('never'),
 np.str_('much'),
 np.str_('japan'),
 np.str_('im'),
 np.str_('bomber'),
 np.str_('wreck'),
 np.str_('great'),
 np.str_('11'),
 np.str_('latest'),
 np.str_('homes'),
 np.str_('every'),
 np.str_('8'),
 np.str_('typhoon'),
 np.str_('obama'),
 np.str_('fear'),
 np.str_('any'),
 np.str_('where'),
 np.str_('under'),
 np.str_('said'),
 np.str_('floods'),
 np.str_('while'),
 np.str_('top'),
 np.str_('getting'),
 np.str_('ever'),
 np.str_('damage'),
 np.str_('content'),
 np.str_('atomic'),
 np.str_('15'),
 np.str_('since'),
 np.str_('injured'),
 np.str_('feel'),
 np.str_('everyone'),
 np.str_('6'),
 np.str_('near'),
 np.str_('m'),
 np.str_('flood'),
 np.str_('flames'),
 np.str_('come'),
 np.str_('16'),
 np.str_('without'),
 np.str_('wild'),
 np.str_('these'),
 np.str_('summer'),
 np.str_('military'),
 np.str_('found'),
 np.str_('cross'),
 np.str_('stop'),
 np.str_('most'),
 np.str_('hope'),
 np.str_('flooding'),
 np.str_('08'),
 np.str_('which'),
 np.str_('shit'),
 np.str_('oil'),
 np.str_('hit'),
 np.str_('food'),
 np.str_('before'),
 np.str_('times'),
 np.str_('state'),
 np.str_('sinking'),
 np.str_('plan'),
 np.str_('evacuation'),
 np.str_('during'),
 np.str_('debris'),
 np.str_('coming'),
 np.str_('check'),
 np.str_('fucking'),
 np.str_('free'),
 np.str_('explosion'),
 np.str_('cause'),
 np.str_('bloody'),
 np.str_('well'),
 np.str_('weapons'),
 np.str_('weapon'),
 np.str_('truck'),
 np.str_('little'),
 np.str_('always'),
 np.str_('10'),
 np.str_('wounded'),
 np.str_('until'),
 np.str_('red'),
 np.str_('rain'),
 np.str_('next'),
 np.str_('made'),
 np.str_('injury'),
 np.str_('injuries'),
 np.str_('hurricane'),
 np.str_('face'),
 np.str_('end'),
 np.str_('bad'),
 np.str_('again'),
 np.str_('wind'),
 np.str_('thunderstorm'),
 np.str_('smoke'),
 np.str_('severe'),
 np.str_('run'),
 np.str_('p'),
 np.str_('night'),
 np.str_('movie'),
 np.str_('lightning'),
 np.str_('heat'),
 np.str_('fatalities'),
 np.str_('fall'),
 np.str_('evacuate'),
 np.str_('confirmed'),
 np.str_('big'),
 np.str_('area'),
 np.str_('70'),
 np.str_('set'),
 np.str_('rescue'),
 np.str_('natural'),
 np.str_('looks'),
 np.str_('iran'),
 np.str_('high'),
 np.str_('earthquake'),
 np.str_('china'),
 np.str_('boy'),
 np.str_('air'),
 np.str_('40'),
 np.str_('05'),
 np.str_('whole'),
 np.str_('thunder'),
 np.str_('through'),
 np.str_('says'),
 np.str_('save'),
 np.str_('refugees'),
 np.str_('re'),
 np.str_('panic'),
 np.str_('outbreak'),
 np.str_('migrants'),
 np.str_('house'),
 np.str_('head'),
 np.str_('hazard'),
 np.str_('hail'),
 np.str_('family'),
 np.str_('failure'),
 np.str_('devastated'),
 np.str_('destroy'),
 np.str_('derailment'),
 np.str_('d'),
 np.str_('change'),
 np.str_('bus'),
 np.str_('bag'),
 np.str_('ambulance'),
 np.str_('7'),
 np.str_('terrorist'),
 np.str_('survive'),
 np.str_('services'),
 np.str_('screaming'),
 np.str_('saudi'),
 np.str_('post'),
 np.str_('national'),
 np.str_('murder'),
 np.str_('loud'),
 np.str_('liked'),
 np.str_('gonna'),
 np.str_('explode'),
 np.str_('collided'),
 np.str_('blood'),
 np.str_('attacked'),
 np.str_('warning'),
 np.str_('update'),
 np.str_('tonight'),
 np.str_('terrorism'),
 np.str_('sinkhole'),
 np.str_('service'),
 np.str_('reunion'),
 np.str_('rescuers'),
 np.str_('report'),
 np.str_('real'),
 np.str_('photo'),
 np.str_('massacre'),
 np.str_('lives'),
 np.str_('harm'),
 np.str_('drought'),
 np.str_('displaced'),
 np.str_('charged'),
 np.str_('also'),
 np.str_('30'),
 np.str_('wrecked'),
 np.str_('windstorm'),
 np.str_('twitter'),
 np.str_('twister'),
 np.str_('traffic'),
 np.str_('survivors'),
 np.str_('self'),
 np.str_('rescued'),
 np.str_('released'),
 np.str_('game'),
 np.str_('fuck'),
 np.str_('destruction'),
 np.str_('destroyed'),
 np.str_('crush'),
 np.str_('collision'),
 np.str_('calgary'),
 np.str_('breaking'),
 np.str_('bags'),
 np.str_('0'),
 np.str_('wreckage'),
 np.str_('women'),
 np.str_('white'),
 np.str_('violent'),
 np.str_('trauma'),
 np.str_('tragedy'),
 np.str_('things'),
 np.str_('survived'),
 np.str_('spill'),
 np.str_('sandstorm'),
 np.str_('road'),
 np.str_('rioting'),
 np.str_('put'),
 np.str_('ok'),
 np.str_('music'),
 np.str_('missing'),
 np.str_('long'),
 np.str_('landslide'),
 np.str_('keep'),
 np.str_('heart'),
 np.str_('girl'),
 np.str_('deluge'),
 np.str_('deaths'),
 np.str_('curfew'),
 np.str_('crashed'),
 np.str_('boat'),
 np.str_('battle'),
 np.str_('august'),
 np.str_('airplane'),
 np.str_('structural'),
 np.str_('south'),
 np.str_('screamed'),
 np.str_('phone'),
 np.str_('other'),
 np.str_('oh'),
 np.str_('mosque'),
 np.str_('horrible'),
 np.str_('dust'),
 np.str_('detonate'),
 np.str_('cliff'),
 np.str_('catastrophe'),
 np.str_('call'),
 np.str_('bombed'),
 np.str_('away'),
 np.str_('apocalypse'),
 np.str_('woman'),
 np.str_('whirlwind'),
 np.str_('use'),
 np.str_('thank'),
 np.str_('t'),
 np.str_('stock'),
 np.str_('someone'),
 np.str_('show'),
 np.str_('saw'),
 np.str_('ruin'),
 np.str_('riot'),
 np.str_('quarantine'),
 np.str_('kills'),
 np.str_('island'),
 np.str_('investigators'),
 np.str_('hostages'),
 np.str_('famine'),
 np.str_('danger'),
 np.str_('armageddon'),
 np.str_('zone'),
 np.str_('traumatised'),
 np.str_('tornado'),
 np.str_('suspect'),
 np.str_('story'),
 np.str_('screams'),
 np.str_('quarantined'),
 np.str_('power'),
 np.str_('part'),
 np.str_('pandemonium'),
 np.str_('n'),
 np.str_('must'),
 np.str_('light'),
 np.str_('lava'),
 np.str_('government'),
 np.str_('engulfed'),
 np.str_('derailed'),
 np.str_('deal'),
 np.str_('collapsed'),
 np.str_('came'),
 np.str_('blown'),
 np.str_('better'),
 np.str_('bagging'),
 np.str_('around'),
 np.str_('against'),
 np.str_('affected'),
 np.str_('wave'),
 np.str_('wanna'),
 np.str_('trapped'),
 np.str_('sure'),
 np.str_('sunk'),
 np.str_('send'),
 np.str_('river'),
 np.str_('razed'),
 np.str_('o'),
 np.str_('murderer'),
 np.str_('mudslide'),
 np.str_('meltdown'),
 np.str_('market'),
 np.str_('isis'),
 np.str_('india'),
 np.str_('hundreds'),
 np.str_('hostage'),
 np.str_('hazardous'),
 np.str_('half'),
 np.str_('group'),
 np.str_('flattened'),
 np.str_('exploded'),
 np.str_('electrocuted'),
 np.str_('ebay'),
 np.str_('drown'),
 np.str_('dont'),
 np.str_('devastation'),
 np.str_('derail'),
 np.str_('burned'),
 np.str_('bang'),
 np.str_('baby'),
 np.str_('b'),
 np.str_('went'),
 np.str_('week'),
 np.str_('volcano'),
 np.str_('thing'),
 np.str_('st'),
 np.str_('obliterated'),
 np.str_('minute'),
 np.str_('land'),
 np.str_('hijacker'),
 np.str_('heard'),
 np.str_('doing'),
 np.str_('demolish'),
 np.str_('chemical'),
 np.str_('casualties'),
 np.str_('care'),
 np.str_('bridge'),
 np.str_('used'),
 np.str_('tsunami'),
 np.str_('trouble'),
 np.str_('three'),
 np.str_('thought'),
 np.str_('song'),
 np.str_('something'),
 np.str_('responders'),
 np.str_('past'),
 np.str_('officials'),
 np.str_('lot'),
 np.str_('least'),
 np.str_('kill'),
 np.str_('inundated'),
 np.str_('hijacking'),
 np.str_('goes'),
 np.str_('few'),
 np.str_('drowning'),
 np.str_('desolation'),
 np.str_('crushed'),
 np.str_('collide'),
 np.str_('caused'),
 np.str_('anniversary'),
 np.str_('00'),
 np.str_('yet'),
 np.str_('wounds'),
 np.str_('sue'),
 np.str_('soon'),
 np.str_('shoulder'),
 np.str_('security'),
 np.str_('rainstorm'),
 np.str_('r'),
 np.str_('prebreak'),
 np.str_('possible'),
 np.str_('plane'),
 np.str_('pkk'),
 np.str_('panicking'),
 np.str_('obliteration'),
 np.str_('obliterate'),
 np.str_('left'),
 np.str_('kids'),
 np.str_('hellfire'),
 np.str_('fedex'),
 np.str_('evacuated'),
 np.str_('e'),
 np.str_('due'),
 np.str_('detonated'),
 np.str_('days'),
 np.str_('cyclone'),
 np.str_('catastrophic'),
 np.str_('c'),
 np.str_('brown'),
 np.str_('book'),
 np.str_('blew'),
 np.str_('blazing'),
 np.str_('blast'),
 np.str_('avalanche'),
 np.str_('annihilated'),
 np.str_('airport'),
 np.str_('upheaval'),
 np.str_('trying'),
 np.str_('thanks'),
 np.str_('stand'),
 np.str_('sound'),
 np.str_('snowstorm'),
 np.str_('sirens'),
 np.str_('offensive'),
 np.str_('north'),
 np.str_('mp'),
 np.str_('men'),
 np.str_('making'),
 np.str_('issues'),
 np.str_('fun'),
 np.str_('fatality'),
 np.str_('done'),
 np.str_('died'),
 np.str_('detonation'),
 np.str_('county'),
 np.str_('cool'),
 np.str_('bleeding'),
 np.str_('believe'),
 np.str_('beautiful'),
 np.str_('arson'),
 np.str_('50'),
 np.str_('words'),
 np.str_('very'),
 np.str_('tomorrow'),
 np.str_('second'),
 np.str_('remember'),
 np.str_('policy'),
 np.str_('place'),
 np.str_('pic'),
 np.str_('nothing'),
 np.str_('media'),
 np.str_('longer'),
 np.str_('line'),
 np.str_('israeli'),
 np.str_('health'),
 np.str_('fight'),
 np.str_('electrocute'),
 np.str_('drowned'),
 np.str_('demolished'),
 np.str_('casualty'),
 np.str_('bush'),
 np.str_('both'),
 np.str_('bioterror'),
 np.str_('25'),
 np.str_('06'),
 np.str_('ur'),
 np.str_('united'),
 np.str_('turkey'),
 np.str_('stretcher'),
 np.str_('site'),
 np.str_('shot'),
 np.str_('shooting'),
 np.str_('seismic'),
 np.str_('plans'),
 np.str_('peace'),
 np.str_('nowplaying'),
 np.str_('lost'),
 np.str_('job'),
 np.str_('islam'),
 np.str_('inside'),
 np.str_('hours'),
 np.str_('hijack'),
 np.str_('helicopter'),
 np.str_('hear'),
 np.str_('guys'),
 np.str_('fan'),
 np.str_('die'),
 np.str_('demolition'),
 np.str_('deluged'),
 np.str_('building'),
 np.str_('america'),
 np.str_('actually'),
 np.str_('yes'),
 np.str_('yeah'),
 np.str_('x'),
 np.str_('watching'),
 np.str_('wait'),
 np.str_('tell'),
 np.str_('swallowed'),
 np.str_('support'),
 np.str_('such'),
 np.str_('start'),
 np.str_('soudelor'),
 np.str_('side'),
 np.str_('rubble'),
 np.str_('reactor'),
 np.str_('play'),
 np.str_('officer'),
 np.str_('memories'),
 np.str_('horror'),
 np.str_('hell'),
 np.str_('having'),
 np.str_('find'),
 np.str_('eyewitness'),
 np.str_('desolate'),
 np.str_('control'),
 np.str_('children'),
 np.str_('anything'),
 np.str_('already'),
 np.str_('almost'),
 np.str_('aircraft'),
 np.str_('abc'),
 np.str_('yourself'),
 np.str_('west'),
 np.str_('usa'),
 np.str_('tv'),
 np.str_('team'),
 np.str_('stay'),
 np.str_('searching'),
 np.str_('saved'),
 np.str_('same'),
 np.str_('rd'),
 np.str_('probably'),
 np.str_('photos'),
 np.str_('person'),
 np.str_('outside'),
 np.str_('order'),
 np.str_('nearby'),
 np.str_('maybe'),
 np.str_('literally'),
 np.str_('history'),
 np.str_('hat'),
 np.str_('far'),
 np.str_('data'),
 np.str_('crews'),
 np.str_('conclusively'),
 np.str_('business'),
 np.str_('blight'),
 np.str_('bioterrorism'),
 np.str_('bc'),
 np.str_('american'),
 np.str_('waves'),
 np.str_('texas'),
 np.str_('street'),
 np.str_('siren'),
 np.str_('rise'),
 np.str_('reuters'),
 np.str_('pakistan'),
 np.str_('manslaughter'),
 np.str_('leather'),
 np.str_('hey'),
 np.str_('hailstorm'),
 np.str_('friends'),
 np.str_('feeling'),
 np.str_('eyes'),
 np.str_('everything'),
 np.str_('declares'),
 np.str_('country'),
 np.str_('center'),
 np.str_('bodies'),
 np.str_('aug'),
 np.str_('amid'),
 np.str_('ago'),
 np.str_('ablaze'),
 np.str_('01'),
 np.str_('youth'),
 np.str_('wake'),
 np.str_('utc'),
 np.str_('trench'),
 np.str_('talk'),
 np.str_('property'),
 np.str_('picking'),
 np.str_('own'),
 np.str_('others'),
 np.str_('online'),
 np.str_('omg'),
 np.str_('okay'),
 np.str_('name'),
 np.str_('myself'),
 np.str_('money'),
 np.str_('meek'),
 np.str_('makes'),
 np.str_('leave'),
 np.str_('lab'),
 np.str_('la'),
 np.str_('gets'),
 np.str_('front'),
 np.str_('flag'),
 np.str_('effect'),
 np.str_('crisis'),
 np.str_('blaze'),
 np.str_('17'),
 np.str_('wrong'),
 np.str_('w'),
 np.str_('trains'),
 np.str_('though'),
 np.str_('space'),
 np.str_('saipan'),
 np.str_('reason'),
 np.str_('radio'),
 np.str_('pretty'),
 np.str_('pick'),
 np.str_('move'),
 np.str_('major'),
 np.str_('low'),
 np.str_('lord'),
 np.str_('listen'),
 np.str_('image'),
 np.str_('huge'),
 np.str_('happy'),
 np.str_('guy'),
 np.str_('gun'),
 np.str_('green'),
 np.str_('flash'),
 np.str_('feared'),
 np.str_('fast'),
 np.str_('damn'),
 np.str_('course'),
 np.str_('cnn'),
 np.str_('class'),
 np.str_('child'),
 np.str_('chance'),
 np.str_('caught'),
 np.str_('cant'),
 np.str_('called'),
 np.str_('blue'),
 np.str_('bestnaijamade'),
 np.str_('become'),
 np.str_('bar'),
 np.str_('banned'),
 np.str_('ball'),
 np.str_('annihilation'),
 np.str_('20'),
 np.str_('12'),
 np.str_('worst'),
 np.str_('win'),
 np.str_('vehicle'),
 np.str_('town'),
 np.str_('totally'),
 np.str_('toddler'),
 np.str_('temple'),
 np.str_('taken'),
 np.str_('spot'),
 np.str_('sorry'),
 np.str_('signs'),
 np.str_('ship'),
 np.str_('sensor'),
 np.str_('russian'),
 np.str_('russia'),
 np.str_('patience'),
 np.str_('nearly'),
 np.str_('level'),
 np.str_('laughing'),
 np.str_('ladies'),
 np.str_('jobs'),
 np.str_('human'),
 np.str_('east'),
 np.str_('disea'),
 np.str_('daily'),
 np.str_('couple'),
 np.str_('co'),
 np.str_('case'),
 np.str_('british'),
 np.str_('bigger'),
 np.str_('bbc'),
 np.str_('australia'),
 np.str_('action'),
 np.str_('across'),
 np.str_('18'),
 np.str_('yours'),
 np.str_('womens'),
 np.str_('village'),
 np.str_('uk'),
 np.str_('try'),
 np.str_('transport'),
 np.str_('star'),
 np.str_('sign'),
 np.str_('seen'),
 np.str_('running'),
 np.str_('rock'),
 np.str_('projected'),
 np.str_('once'),
 np.str_('official'),
 np.str_('needs'),
 np.str_('mount'),
 np.str_('mom'),
 np.str_('might'),
 np.str_('mayhem'),
 np.str_('looking'),
 np.str_('knock'),
 np.str_('insurance'),
 np.str_('instead'),
 np.str_('hollywood'),
 np.str_('hate'),
 np.str_('haha'),
 np.str_('gop'),
 np.str_('fukushima'),
 np.str_('finally'),
 np.str_('favorite'),
 np.str_('eye'),
 np.str_('experts'),
 np.str_('entire'),
 np.str_('department'),
 np.str_('crazy'),
 np.str_('computers'),
 np.str_('coaches'),
 np.str_('christian'),
 np.str_('ca'),
 np.str_('blizzard'),
 np.str_('apollo'),
 np.str_('anyone'),
 np.str_('wow'),
 np.str_('wednesday'),
 np.str_('vs'),
 np.str_('virgin'),
 np.str_('tweet'),
 np.str_('truth'),
 np.str_('trust'),
 np.str_('takes'),
 np.str_('sky'),
 np.str_('sex'),
 np.str_('sea'),
 np.str_('refugio'),
 np.str_('poor'),
 np.str_('planned'),
 np.str_('pay'),
 np.str_('park'),
 np.str_('pain'),
 np.str_('nagasaki'),
 np.str_('muslims'),
 np.str_('morning'),
 np.str_('miners'),
 np.str_('michael'),
 np.str_('marks'),
 np.str_('mad'),
 np.str_('issued'),
 np.str_('israel'),
 np.str_('ignition'),
 np.str_('houses'),
 np.str_('heavy'),
 np.str_('hard'),
 np.str_('happened'),
 np.str_('global'),
 np.str_('giant'),
 np.str_('gbbo'),
 np.str_('fox'),
 np.str_('emmerdale'),
 np.str_('driver'),
 np.str_('drive'),
 np.str_('dog'),
 np.str_('disease'),
 np.str_('costlier'),
 np.str_('cars'),
 np.str_('camp'),
 np.str_('beach'),
 np.str_('arsonist'),
 np.str_('animal'),
 np.str_('angry'),
 np.str_('alone'),
 np.str_('added'),
 np.str_('13'),
 np.str_('100'),
 np.str_('young'),
 np.str_('york'),
 np.str_('wonder'),
 np.str_('wanted'),
 np.str_('v'),
 np.str_('turn'),
 np.str_('taking'),
 np.str_('subreddits'),
 np.str_('sounds'),
 np.str_('silver'),
 np.str_('scene'),
 np.str_('scared'),
 np.str_('sad'),
 np.str_('rly'),
 np.str_('reports'),
 np.str_('reported'),
 np.str_('ready'),
 np.str_('quiz'),
 np.str_('public'),
 np.str_('pradesh'),
 np.str_('ppl'),
 np.str_('playing'),
 np.str_('parole'),
 np.str_('pamela'),
 np.str_('pakistani'),
 np.str_('outrage'),
 np.str_('niggas'),
 np.str_('myanmar'),
 np.str_('madhya'),
 np.str_('link'),
 np.str_('learn'),
 np.str_('large'),
 np.str_('give'),
 np.str_('gems'),
 np.str_('gave'),
 np.str_('gas'),
 np.str_('galactic'),
 np.str_('funtenna'),
 np.str_('france'),
 np.str_('former'),
 np.str_('follow'),
 np.str_('film'),
 np.str_('else'),
 np.str_('earth'),
 np.str_('driving'),
 np.str_('drake'),
 np.str_('downtown'),
 np.str_('comes'),
 np.str_('closed'),
 ...]

In [ ]:
word_in_vocab[:10]

['',
 '[UNK]',
 np.str_('the'),
 np.str_('a'),
 np.str_('in'),
 np.str_('to'),
 np.str_('of'),
 np.str_('i'),
 np.str_('and'),
 np.str_('is')]

In [14]:
word_in_vocab[-10:]

[np.str_('muttatek'),
 np.str_('mutt'),
 np.str_('mutilated'),
 np.str_('mutekmontreal'),
 np.str_('mute'),
 np.str_('mustering'),
 np.str_('mustard'),
 np.str_('mustachemurse'),
 np.str_('musk'),
 np.str_('musicvideo')]

In [15]:
# How many words in The Vocabulary
len(word_in_vocab)

10000

**Creating an Embedding using Embedding Layer**

In [16]:
from tensorflow.keras import layers

In [17]:
embedding = layers.Embedding(input_dim=max_vocab_length,
                             output_dim=128,
                             embeddings_initializer="uniform")
embedding

In [18]:
text_vectorizer(["There is a flood in my street "])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[ 66,   9,   3, 235,   4,  14, 732,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [19]:
embedding(text_vectorizer(["There is a flood in my street "]))

<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[ 0.02563012,  0.02443785, -0.00801138, ...,  0.03856829,
          0.02816233, -0.00058571],
        [ 0.0286821 ,  0.02368214, -0.02571404, ..., -0.04779696,
         -0.01253365,  0.02951557],
        [ 0.02289278, -0.02550446, -0.02396481, ...,  0.04362574,
         -0.04734213, -0.04675185],
        ...,
        [-0.01849391, -0.0062653 ,  0.02316346, ..., -0.01903631,
         -0.01674321,  0.0226395 ],
        [-0.01849391, -0.0062653 ,  0.02316346, ..., -0.01903631,
         -0.01674321,  0.0226395 ],
        [-0.01849391, -0.0062653 ,  0.02316346, ..., -0.01903631,
         -0.01674321,  0.0226395 ]]], dtype=float32)>

In [20]:
embedding(text_vectorizer(["There is a flood in my street "]))[0][0]

<tf.Tensor: shape=(128,), dtype=float32, numpy=
array([ 0.02563012,  0.02443785, -0.00801138,  0.0291079 ,  0.03801285,
        0.04000937, -0.00282396,  0.02510964, -0.01034052, -0.04655944,
       -0.04450425,  0.04541658, -0.00122075, -0.01571251, -0.0298558 ,
       -0.03157352,  0.04763756,  0.04678006,  0.00060457,  0.02145299,
       -0.02193271,  0.01090153, -0.034913  , -0.01004999,  0.01903046,
       -0.00598888, -0.01536022, -0.01817109, -0.04867756,  0.04638357,
       -0.01570423,  0.0116006 , -0.01488532,  0.02655754, -0.03758273,
        0.01985023,  0.0317762 , -0.00265076,  0.00781504,  0.03775654,
        0.00049558, -0.04180051,  0.02609864,  0.03904724, -0.04257793,
        0.02024415, -0.02702694, -0.02730409,  0.02741623, -0.00457428,
       -0.04519718,  0.00307462,  0.04391554, -0.03920887,  0.01848289,
       -0.03678744,  0.03925164,  0.00146177,  0.00835747,  0.02420584,
       -0.02854986, -0.03085946,  0.03390206, -0.00291357, -0.01473895,
        0.03452252,  0.04377825, -0.00225861,  0.00840769, -0.00383497,
        0.03110752, -0.03468573,  0.00228567, -0.03218739, -0.01750209,
        0.04691687, -0.04165525,  0.00457226, -0.00903627, -0.02783383,
        0.04494277, -0.03223468, -0.03441323, -0.04660933,  0.04145021,
        0.03020406,  0.04288974,  0.02279861,  0.01699778,  0.04610267,
       -0.00097013, -0.04695297, -0.00568042, -0.02147691,  0.00069169,
        0.03462193, -0.02562679,  0.0263874 , -0.04008538,  0.03556441,
        0.0048339 ,  0.0479908 , -0.00817939,  0.04782993,  0.01536986,
       -0.02150634,  0.00919329, -0.04724235,  0.0408151 , -0.04983765,
        0.02102307,  0.00019341, -0.01120305, -0.00640891, -0.01422467,
       -0.02981963,  0.02083335,  0.01011834,  0.03003777, -0.01195121,
        0.01955814,  0.02911581,  0.04828588, -0.00818205,  0.04448033,
        0.03856829,  0.02816233, -0.00058571], dtype=float32)>

Nice, we have Converted texts into numbers

Model 1 LSTM

In [21]:
from tensorflow.keras import layers

inputs = layers.Input(shape=(1,),dtype="string")
x=text_vectorizer(inputs)
x=embedding(x)

x=layers.LSTM(64)(x)

outputs = layers.Dense(1,activation="sigmoid")(x)

lstm_model = tf.keras.Model(inputs, outputs, name="LSTM_model")

In [ ]:
lstm_model.summary() # this is are the model architecture

Model: "LSTM_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 1)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ text_vectorization              │ (None, 15)             │             0 │
│ (TextVectorization)             │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding (Embedding)           │ (None, 15, 128)        │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,329,473 (5.07 MB)

 Trainable params: 1,329,473 (5.07 MB)

 Non-trainable params: 0 (0.00 B)

In [22]:
lstm_model.compile(loss="binary_crossentropy",
                   optimizer=tf.keras.optimizers.Adam(),
                   metrics=["accuracy"])

In [23]:
lstm_model_history = lstm_model.fit(train_sentences,
                                    train_labels,
                                     epochs=5,
                                     validation_data=(val_sentences,val_labels))

Epoch 1/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 9s 25ms/step - accuracy: 0.7475 - loss: 0.5108 - val_accuracy: 0.7953 - val_loss: 0.4667
Epoch 2/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - accuracy: 0.8695 - loss: 0.3230 - val_accuracy: 0.7861 - val_loss: 0.4785
Epoch 3/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 7s 31ms/step - accuracy: 0.9175 - loss: 0.2218 - val_accuracy: 0.7874 - val_loss: 0.5363
Epoch 4/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - accuracy: 0.9380 - loss: 0.1691 - val_accuracy: 0.7677 - val_loss: 0.6432
Epoch 5/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 6s 27ms/step - accuracy: 0.9597 - loss: 0.1152 - val_accuracy: 0.7822 - val_loss: 0.6226

In [24]:
# Make predictions with LSTM model

lstm_model_pred_probs = lstm_model.predict(val_sentences)
lstm_model_pred_probs[:10]

24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step

array([[0.7878779 ],
       [0.8310919 ],
       [0.9993815 ],
       [0.03556867],
       [0.0089321 ],
       [0.9994435 ],
       [0.9420705 ],
       [0.99963385],
       [0.9990506 ],
       [0.13347505]], dtype=float32)

In [28]:
# Convert LSTM model probabilities to labels

lstm_model_preds = tf.squeeze(tf.round(lstm_model_pred_probs))

In [26]:
lstm_model_preds[:10]

In [27]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_result(y_True,y_pred):

  model_accuracy= accuracy_score(y_True,y_pred)*100
  model_precision , model_recal, model_f1, _= precision_recall_fscore_support(y_True,y_pred)

  model_results = {"accuracy": model_accuracy,
                   "Precision": model_precision,
                   "f1": model_f1}
  return model_results

In [42]:
#Calculate model 3 results

lstm_model_result = calculate_result(y_True=val_labels,
                                    y_pred=lstm_model_preds.numpy())
lstm_model_result

{'accuracy': 78.21522309711287,
 'Precision': array([0.77555556, 0.79166667]),
 'f1': array([0.80787037, 0.74848485])}

**Model 2 : GRU**

In [32]:
inputs = layers.Input(shape=(1,),dtype="string")

x=text_vectorizer(inputs) # tokenize The text

x= embedding(x) # Creates richer representation

x = layers.GRU(64)(x)

outputs = layers.Dense(1,activation="sigmoid")(x)
gru_model = tf.keras.Model(inputs,outputs,name="GRU_model")

In [33]:
gru_model.summary()

Model: "GRU_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 1)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ text_vectorization              │ (None, 15)             │             0 │
│ (TextVectorization)             │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding (Embedding)           │ (None, 15, 128)        │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 64)             │        37,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,317,313 (5.03 MB)

 Trainable params: 1,317,313 (5.03 MB)

 Non-trainable params: 0 (0.00 B)

In [34]:
gru_model.compile(loss="binary_crossentropy",
                  optimizer=tf.keras.optimizers.Adam(),
                  metrics=["accuracy"])

In [35]:
# Fit the model
gru_model_history = gru_model.fit(train_sentences,
                                  train_labels,
                                  epochs=5,
                                  validation_data=(val_sentences,val_labels))

Epoch 1/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 9s 26ms/step - accuracy: 0.9174 - loss: 0.2105 - val_accuracy: 0.7690 - val_loss: 0.7134
Epoch 2/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9619 - loss: 0.1068 - val_accuracy: 0.7782 - val_loss: 0.7513
Epoch 3/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - accuracy: 0.9705 - loss: 0.0813 - val_accuracy: 0.7585 - val_loss: 1.0665
Epoch 4/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - accuracy: 0.9718 - loss: 0.0681 - val_accuracy: 0.7782 - val_loss: 1.0567
Epoch 5/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 6s 29ms/step - accuracy: 0.9753 - loss: 0.0579 - val_accuracy: 0.7677 - val_loss: 1.0708

In [36]:
# Make Some predictions With Our GRU Model

gru_model_pred_probs = gru_model.predict(val_sentences)
gru_model_pred_probs

24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step

array([[1.25390990e-03],
       [9.47545826e-01],
       [9.99359846e-01],
       [3.27499059e-04],
       [2.35610001e-04],
       [9.99639034e-01],
       [9.64371920e-01],
       [9.99781013e-01],
       [9.99677896e-01],
       [3.79456609e-01],
       [6.79720368e-04],
       [5.06311893e-01],
       [1.65920064e-04],
       [3.83499205e-01],
       [1.17358890e-04],
       [8.24691176e-01],
       [2.69550784e-03],
       [1.67119049e-03],
       [1.93772867e-01],
       [9.99482095e-01],
       [9.99840200e-01],
       [8.65082038e-05],
       [8.85052085e-01],
       [2.12336355e-03],
       [9.99650478e-01],
       [9.99756575e-01],
       [5.08439802e-02],
       [6.89961074e-04],
       [1.24388433e-03],
       [2.99661785e-01],
       [9.99232054e-01],
       [1.33048370e-02],
       [2.66542006e-02],
       [9.98156727e-04],
       [4.15562034e-01],
       [7.59241343e-01],
       [9.99493301e-01],
       [2.04097062e-01],
       [1.40691593e-01],
       [9.99843597e-01],
       [5.55769801e-01],
       [8.49892444e-04],
       [2.54339427e-02],
       [2.31587488e-04],
       [8.65161240e-01],
       [9.99036551e-01],
       [1.86699852e-01],
       [9.57995594e-01],
       [4.32026759e-03],
       [1.37409437e-02],
       [3.90672125e-03],
       [5.50997615e-01],
       [3.39825422e-01],
       [9.09142256e-01],
       [2.07328394e-01],
       [2.81849504e-03],
       [1.50455115e-02],
       [9.99696255e-01],
       [7.51949310e-01],
       [1.19273878e-04],
       [3.99373062e-02],
       [9.99736607e-01],
       [9.96152520e-01],
       [2.53740884e-02],
       [9.98739719e-01],
       [9.99835074e-01],
       [7.94892430e-01],
       [9.87205327e-01],
       [2.26598516e-01],
       [8.95063758e-01],
       [2.89154574e-02],
       [1.69467762e-01],
       [9.99889851e-01],
       [3.73543962e-03],
       [9.92138386e-01],
       [9.39283907e-01],
       [1.66166842e-01],
       [9.98027861e-01],
       [1.71952501e-01],
       [4.19249833e-01],
       [2.85202346e-04],
       [1.84390083e-01],
       [9.99821246e-01],
       [6.45499269e-04],
       [2.37113051e-03],
       [1.41297234e-03],
       [3.63241183e-04],
       [2.79572938e-04],
       [3.18280363e-04],
       [9.99225557e-01],
       [9.99434233e-01],
       [2.62800721e-04],
       [6.91262260e-02],
       [2.44215102e-04],
       [9.99652684e-01],
       [7.62676179e-01],
       [3.40400785e-01],
       [9.99870479e-01],
       [9.99252021e-01],
       [1.32146608e-02],
       [9.99929249e-01],
       [5.57852769e-03],
       [1.54539201e-04],
       [9.96150732e-01],
       [9.99572873e-01],
       [1.96734499e-02],
       [9.99303937e-01],
       [9.80568290e-01],
       [1.77700189e-04],
       [9.99466538e-01],
       [9.95880902e-01],
       [3.65559533e-02],
       [9.93387043e-01],
       [5.82636218e-04],
       [5.40054927e-04],
       [6.31360352e-01],
       [6.78794801e-01],
       [9.51604486e-01],
       [1.47749931e-02],
       [8.99470353e-04],
       [9.99897897e-01],
       [2.05199103e-04],
       [1.93663000e-04],
       [9.87495899e-01],
       [7.06891937e-04],
       [6.38733432e-03],
       [4.73695900e-03],
       [1.68839688e-04],
       [2.39779800e-03],
       [6.30796432e-01],
       [9.27673071e-04],
       [9.99897897e-01],
       [9.99939322e-01],
       [9.99756575e-01],
       [9.90189910e-01],
       [1.68278662e-03],
       [9.99630451e-01],
       [2.18515411e-01],
       [1.55728683e-02],
       [1.07078778e-03],
       [9.99896944e-01],
       [2.45419413e-01],
       [3.83499205e-01],
       [9.98234808e-01],
       [2.22856849e-01],
       [8.00054520e-03],
       [7.57627931e-05],
       [3.28105642e-04],
       [7.62263499e-03],
       [9.99414027e-01],
       [2.06614044e-04],
       [6.35887384e-02],
       [2.11608987e-02],
       [4.46426478e-04],
       [1.97421483e-04],
       [9.94045854e-01],
       [7.89118814e-04],
       [6.13231491e-03],
       [9.99030292e-01],
       [1.84179589e-04],
       [9.98806715e-01],
       [2.00818595e-03],
       [3.40999290e-02],
       [9.99443293e-01],
       [2.19527274e-01],
       [1.30933404e-04],
       [9.99785900e-01],
       [1.37935777e-03],
       [9.99692082e-01],
       [8.87840092e-02],
       [9.98214662e-01],
       [9.87418652e-01],
       [9.92822587e-01],
       [1.03439714e-04],
       [9.99918044e-01],
       [3.12406383e-03],
       [7.25004017e-01],
       [1.79718959e-03],
       [6.87549263e-02],
       [9.99698818e-01],
       [1.66832171e-02],
       [8.63087922e-02],
       [9.99798894e-01],
       [9.99837041e-01],
       [9.99840379e-01],
       [2.49147112e-03],
       [6.99363276e-03],
       [9.99832392e-01],
       [7.43721757e-05],
       [1.71822132e-04],
       [6.83737686e-03],
       [1.30277185e-03],
       [3.45846463e-04],
       [2.84938375e-04],
       [1.56460505e-04],
       [9.13317956e-04],
       [1.53758924e-03],
       [2.08647526e-03],
       [9.98829961e-01],
       [8.91498383e-03],
       [5.74443102e-01],
       [9.94338155e-01],
       [9.99065697e-01],
       [1.40867278e-01],
       [1.10078126e-03],
       [9.99925315e-01],
       [9.99478102e-01],
       [9.99723315e-01],
       [8.39114308e-01],
       [9.92247939e-01],
       [3.75831942e-03],
       [9.99690473e-01],
       [6.58856472e-04],
       [1.71764323e-03],
       [2.18252040e-04],
       [1.66990125e-04],
       [8.54521573e-01],
       [9.95139003e-01],
       [9.98167574e-01],
       [2.72745699e-01],
       [9.77013230e-01],
       [8.58388126e-01],
       [5.33771841e-03],
       [1.49352103e-03],
       [9.99659240e-01],
       [1.38245495e-02],
       [4.53445420e-04],
       [9.99807596e-01],
       [9.94303584e-01],
       [9.93745208e-01],
       [2.87070725e-04],
       [5.06889448e-03],
       [9.98913944e-01],
       [2.44894117e-01],
       [6.43749177e-01],
       [2.10521951e-01],
       [5.10377586e-01],
       [1.00125499e-01],
       [6.45192862e-02],
       [2.13035964e-03],
       [9.83936906e-01],
       [1.29967064e-01],
       [9.99738812e-01],
       [9.99646902e-01],
       [7.49813742e-04],
       [1.70777130e-04],
       [9.99592662e-01],
       [8.66602734e-03],
       [3.02045494e-01],
       [1.33770227e-01],
       [3.67532077e-04],
       [9.99283075e-01],
       [7.21729448e-05],
       [6.06551114e-03],
       [9.99344528e-01],
       [1.87263459e-01],
       [9.99868870e-01],
       [9.99877870e-01],
       [3.64261977e-02],
       [1.54024761e-04],
       [1.14822304e-02],
       [3.89659125e-03],
       [1.56990718e-04],
       [9.99501288e-01],
       [9.99447346e-01],
       [1.28095234e-02],
       [9.98930514e-01],
       [7.24432757e-04],
       [1.49731636e-02],
       [2.60822999e-04],
       [2.74751112e-02],
       [6.41910185e-04],
       [9.97439563e-01],
       [8.07182118e-02],
       [1.86354504e-04],
       [9.99501705e-01],
       [2.46201438e-04],
       [5.66679228e-04],
       [9.99584675e-01],
       [5.75377699e-03],
       [9.52102058e-03],
       [3.00902757e-04],
       [9.99305606e-01],
       [5.03578484e-02],
       [7.81803012e-01],
       [7.00131233e-04],
       [9.99071896e-01],
       [2.40606070e-02],
       [9.98969495e-01],
       [3.42686065e-02],
       [9.39258337e-01],
       [8.92632723e-01],
       [9.51908588e-01],
       [5.58217227e-01],
       [1.21871789e-03],
       [9.54550803e-01],
       [6.40730606e-03],
       [9.12568159e-03],
       [1.35016628e-03],
       [7.53244638e-01],
       [5.63260510e-05],
       [5.48177911e-03],
       [6.52668579e-03],
       [9.99813974e-01],
       [2.30082704e-04],
       [1.48442477e-01],
       [5.18413913e-03],
       [3.21135193e-01],
       [2.90375620e-01],
       [2.05191853e-03],
       [2.54558225e-04],
       [9.99200881e-01],
       [1.43471107e-01],
       [5.01988649e-01],
       [9.99918699e-01],
       [1.43750600e-04],
       [9.97619569e-01],
       [1.68713048e-01],
       [8.41809623e-03],
       [1.23602353e-01],
       [1.84770231e-03],
       [2.44110376e-02],
       [9.98719394e-01],
       [4.64671291e-03],
       [9.99565363e-01],
       [2.05740377e-01],
       [2.73496786e-04],
       [9.99701858e-01],
       [4.72431362e-04],
       [9.99806941e-01],
       [5.10219904e-03],
       [1.73279294e-03],
       [9.99728382e-01],
       [1.88181791e-02],
       [3.10264208e-04],
       [9.99365568e-01],
       [9.30309878e-04],
       [1.10351644e-03],
       [8.43739212e-02],
       [3.83104712e-01],
       [5.20833535e-04],
       [2.67036282e-03],
       [9.99602020e-01],
       [9.99728262e-01],
       [9.99112427e-01],
       [2.06662148e-01],
       [9.81317580e-01],
       [6.77087903e-01],
       [4.90659708e-03],
       [7.89767364e-04],
       [6.86653554e-02],
       [8.44193846e-02],
       [2.49502162e-04],
       [1.02486671e-03],
       [1.66476537e-02],
       [2.50563957e-04],
       [9.99693692e-01],
       [9.99756575e-01],
       [9.99874353e-01],
       [2.53630374e-02],
       [4.43509102e-01],
       [2.94248253e-01],
       [3.08162998e-03],
       [9.79869545e-01],
       [6.36300802e-01],
       [4.90206934e-04],
       [9.97244031e-04],
       [5.92653232e-04],
       [5.55800438e-01],
       [7.09756464e-02],
       [3.31297307e-03],
       [3.06942221e-03],
       [1.28429892e-04],
       [3.77295054e-02],
       [7.54869044e-01],
       [4.03087318e-01],
       [8.86504204e-05],
       [1.99672231e-03],
       [4.62002447e-03],
       [9.99793887e-01],
       [9.92190599e-01],
       [4.84749228e-01],
       [8.70700359e-01],
       [1.48170962e-04],
       [8.35524380e-01],
       [9.99789059e-01],
       [9.46003079e-01],
       [4.89527613e-01],
       [2.75401659e-02],
       [1.44296391e-02],
       [9.99360144e-01],
       [3.77163589e-01],
       [1.10940158e-03],
       [5.37993133e-01],
       [8.09275452e-03],
       [9.99705553e-01],
       [1.64360180e-01],
       [1.96450041e-03],
       [3.52865737e-03],
       [6.36300802e-01],
       [9.99728441e-01],
       [1.98677619e-04],
       [2.77154654e-01],
       [9.99593198e-01],
       [6.04666639e-05],
       [9.99897897e-01],
       [1.07703870e-03],
       [1.89224724e-04],
       [5.31426223e-04],
       [9.98012483e-01],
       [9.96681690e-01],
       [2.28926679e-03],
       [6.20922132e-04],
       [3.21498185e-01],
       [9.99754071e-01],
       [8.46614778e-01],
       [4.11855784e-04],
       [3.33787786e-04],
       [1.95877567e-01],
       [2.26759561e-03],
       [9.99945045e-01],
       [9.97091532e-01],
       [9.99781728e-01],
       [9.99724209e-01],
       [1.25230839e-02],
       [3.19451690e-01],
       [3.22899374e-04],
       [9.99048769e-01],
       [8.11855018e-04],
       [9.91856515e-01],
       [1.10903606e-01],
       [4.17705858e-03],
       [7.24409893e-02],
       [4.51716827e-04],
       [4.22120647e-04],
       [1.16553418e-02],
       [9.80330765e-01],
       [1.41971046e-03],
       [9.99892473e-01],
       [9.99813974e-01],
       [1.50208594e-03],
       [9.47545826e-01],
       [1.49266829e-03],
       [1.10880076e-03],
       [4.91513014e-01],
       [9.99058485e-01],
       [1.33100867e-01],
       [4.38703477e-01],
       [1.61049626e-04],
       [2.03821361e-01],
       [7.23020203e-05],
       [9.99638498e-01],
       [9.99703109e-01],
       [9.99688864e-01],
       [9.98890460e-01],
       [7.64936686e-01],
       [2.68606842e-01],
       [3.37005476e-04],
       [8.38573158e-01],
       [9.95698869e-01],
       [9.99707401e-01],
       [3.02170840e-04],
       [3.15782218e-03],
       [1.69860180e-02],
       [9.99754846e-01],
       [9.99735475e-01],
       [1.22103235e-03],
       [4.00942639e-02],
       [9.99830186e-01],
       [1.71295868e-03],
       [2.24070866e-02],
       [9.99171734e-01],
       [1.05264969e-03],
       [1.23588322e-03],
       [9.99010146e-01],
       [3.42562884e-01],
       [9.74689066e-01],
       [9.99869108e-01],
       [1.25157414e-04],
       [7.66805885e-03],
       [1.35552342e-04],
       [1.28737913e-04],
       [1.01669773e-03],
       [9.99600053e-01],
       [1.91153493e-04],
       [1.28990412e-01],
       [9.89449203e-01],
       [4.50365897e-03],
       [4.70622350e-03],
       [1.03901482e-04],
       [2.47566612e-03],
       [9.99848247e-01],
       [9.98732507e-01],
       [1.69689059e-02],
       [2.12755464e-02],
       [4.25147638e-02],
       [3.60324571e-04],
       [9.99566615e-01],
       [1.02958421e-03],
       [9.95312631e-01],
       [9.94983554e-01],
       [2.36696404e-04],
       [9.95842159e-01],
       [2.05402449e-03],
       [5.46427786e-01],
       [3.72718647e-03],
       [1.66560009e-01],
       [9.34687138e-01],
       [3.91163081e-01],
       [1.90979645e-01],
       [9.22330260e-01],
       [2.77389918e-04],
       [2.62999034e-04],
       [2.65162736e-01],
       [9.70273733e-01],
       [8.47720057e-02],
       [9.99824464e-01],
       [9.99144077e-01],
       [7.62676179e-01],
       [9.74477232e-01],
       [6.30950689e-01],
       [9.21518775e-04],
       [9.99124527e-01],
       [3.44573647e-01],
       [3.49266306e-02],
       [1.72870085e-01],
       [9.96712744e-01],
       [6.29586866e-05],
       [6.29808567e-03],
       [9.17442799e-01],
       [7.77603924e-01],
       [9.99229431e-01],
       [3.55230644e-02],
       [3.04882288e-01],
       [6.76152468e-01],
       [4.24463447e-04],
       [1.82587393e-02],
       [4.21305886e-03],
       [4.81204778e-01],
       [9.40563500e-01],
       [4.08255029e-03],
       [1.30631975e-04],
       [2.72747517e-01],
       [3.44276940e-03],
       [4.92948992e-03],
       [9.80275333e-01],
       [3.02944958e-01],
       [9.99893904e-01],
       [9.99563873e-01],
       [2.39472836e-01],
       [9.99030709e-01],
       [9.99756813e-01],
       [1.36632822e-04],
       [9.99593437e-01],
       [5.31946063e-01],
       [5.94970167e-01],
       [3.35308820e-01],
       [1.23081624e-03],
       [2.70030112e-03],
       [3.54317250e-04],
       [3.24702030e-03],
       [1.44362813e-04],
       [2.88204476e-03],
       [1.14799303e-03],
       [9.99688864e-01],
       [1.52278144e-03],
       [9.96316493e-01],
       [2.82530040e-01],
       [3.21427593e-03],
       [3.04110406e-04],
       [9.99850750e-01],
       [1.62048303e-02],
       [9.99887824e-01],
       [3.20296347e-01],
       [1.56191001e-02],
       [8.93172860e-01],
       [6.00164232e-04],
       [1.88724563e-01],
       [9.99756813e-01],
       [1.79911804e-04],
       [2.44281255e-03],
       [4.58939783e-02],
       [9.99796093e-01],
       [2.46449769e-03],
       [5.01375704e-04],
       [9.98112023e-01],
       [3.30638664e-04],
       [2.55712192e-04],
       [4.47767699e-04],
       [6.81342855e-02],
       [1.74237136e-02],
       [5.01694918e-01],
       [4.18726646e-04],
       [1.34038529e-03],
       [3.37127567e-04],
       [6.13196418e-02],
       [2.01582632e-04],
       [9.97313857e-01],
       [9.99330699e-01],
       [2.20668435e-01],
       [1.82333533e-04],
       [1.01356197e-03],
       [9.99826074e-01],
       [7.22456992e-01],
       [9.99952376e-01],
       [7.28120515e-03],
       [9.49766159e-01],
       [3.53771187e-02],
       [9.90712941e-01],
       [9.97912467e-01],
       [1.68812345e-04],
       [9.99929428e-01],
       [5.53620085e-02],
       [1.68860257e-02],
       [9.99791920e-01],
       [9.68526118e-03],
       [4.54558583e-04],
       [3.40354838e-03],
       [2.24155039e-04],
       [8.37486535e-02],
       [9.99925315e-01],
       [4.47231799e-01],
       [9.99688506e-01],
       [1.30590007e-01],
       [9.99064088e-01],
       [5.45148551e-01],
       [1.07943274e-01],
       [3.66194814e-04],
       [9.94154274e-01],
       [4.26946586e-04],
       [3.22911769e-01],
       [9.99512434e-01],
       [9.96868432e-01],
       [9.99859154e-01],
       [9.99463439e-01],
       [5.14522851e-01],
       [2.03948212e-03],
       [1.76920628e-04],
       [6.27163589e-01],
       [9.61784840e-01],
       [9.99194980e-01],
       [3.54117365e-03],
       [9.23523664e-01],
       [9.99648690e-01],
       [7.76941946e-04],
       [4.40482795e-01],
       [1.90979645e-01],
       [6.49977708e-04],
       [7.86110580e-01],
       [9.93836403e-01],
       [9.99796867e-01],
       [3.34705110e-03],
       [1.37550742e-04],
       [8.99881474e-04],
       [2.69968007e-02],
       [8.11167181e-01],
       [5.96124940e-02],
       [9.79127049e-01],
       [1.55440575e-04],
       [5.92195429e-02],
       [8.49275067e-02],
       [1.22440336e-02],
       [9.99271214e-01],
       [8.73228814e-03],
       [9.96670604e-01],
       [4.99329478e-01],
       [1.07042310e-04],
       [4.50583029e-04],
       [9.99806881e-01],
       [9.58826184e-01],
       [6.49517635e-04],
       [1.13223635e-01],
       [1.30983785e-01],
       [1.68823768e-04],
       [9.99238133e-01],
       [1.19027542e-02],
       [9.74270403e-01],
       [8.39481711e-01],
       [6.53986121e-03],
       [3.37111384e-01],
       [6.79388165e-01],
       [1.00282142e-02],
       [9.95456636e-01],
       [9.26394999e-01],
       [9.41866875e-01],
       [9.99488235e-01],
       [5.93814313e-01],
       [5.73977172e-01],
       [6.29586866e-05],
       [2.66215295e-01],
       [9.97419953e-01],
       [9.99897897e-01],
       [9.99610007e-01],
       [2.50435015e-03],
       [9.99947667e-01],
       [5.83765686e-01],
       [9.99883056e-01],
       [5.83765686e-01],
       [9.99712706e-01],
       [1.24152168e-04],
       [6.72585890e-03],
       [1.21219869e-04],
       [9.99871910e-01],
       [5.45162102e-03],
       [1.00050354e-03],
       [1.15995645e-03],
       [1.14839682e-02],
       [8.86985566e-04],
       [8.72686796e-04],
       [8.90052259e-01],
       [1.94282993e-03],
       [1.83080276e-03],
       [9.71628368e-01],
       [3.07255127e-02],
       [8.49189162e-02],
       [1.58763753e-04],
       [1.43958125e-04],
       [1.55121731e-02],
       [9.65425372e-01],
       [1.31153852e-01],
       [1.27389489e-04],
       [1.74032967e-03],
       [9.88890171e-01],
       [9.99485731e-01],
       [4.04167775e-04],
       [3.73232091e-04],
       [2.14355459e-04],
       [5.22926384e-05],
       [9.99470234e-01],
       [1.43958125e-04],
       [1.87408901e-03],
       [9.99709010e-01],
       [9.99727905e-01],
       [9.99803841e-01],
       [9.99888837e-01],
       [9.99956250e-01],
       [7.13236979e-04],
       [2.75486447e-02],
       [2.63548759e-03],
       [9.99068737e-01],
       [9.99793053e-01],
       [2.93448210e-01],
       [7.79300637e-04],
       [9.98584628e-01],
       [1.58920497e-01],
       [3.68001318e-04],
       [1.86732286e-04],
       [2.36245850e-03],
       [6.75719511e-03],
       [1.62715136e-04],
       [1.33116059e-02],
       [9.95907247e-01],
       [9.99728739e-01],
       [2.78780266e-04],
       [9.99200761e-01],
       [9.95022655e-01],
       [8.41458291e-02],
       [1.21275961e-01],
       [1.21033592e-02],
       [7.10788190e-01],
       [6.96588159e-01],
       [1.79903771e-04]], dtype=float32)

In [37]:
val_labels

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [39]:
# Convert GRU model pred probs to labels

gru_model_preds = tf.squeeze(tf.round(gru_model_pred_probs))
gru_model_preds

<tf.Tensor: shape=(762,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0.],
      dtype=float32)>

In [41]:
# Calculate GRU model results

gru_model_results = calculate_result(y_True=val_labels,
                                      y_pred=gru_model_preds.numpy())
gru_model_results

{'accuracy': 76.77165354330708,
 'Precision': array([0.76043956, 0.77850163]),
 'f1': array([0.79631761, 0.72977099])}

In [43]:
all_model_results= pd.DataFrame({
    "Long Short-Term Memory ": lstm_model_result,
    "Gated Recurent Unit " : gru_model_results
})
all_model_results

,Long Short-Term Memory,Gated Recurent Unit
accuracy,78.215223,76.771654
Precision,"[0.7755555555555556, 0.7916666666666666]","[0.7604395604395604, 0.7785016286644951]"
f1,"[0.8078703703703703, 0.7484848484848485]","[0.7963176064441887, 0.7297709923664122]"

In [53]:
all_model_results= pd.DataFrame({
    "Long Short-Term Memory ": lstm_model_result,
    "Gated Recurent Unit " : gru_model_results
})
all_model_results=all_model_results.transpose()
all_model_results

,accuracy,Precision,f1
Long Short-Term Memory,78.215223,"[0.7755555555555556, 0.7916666666666666]","[0.8078703703703703, 0.7484848484848485]"
Gated Recurent Unit,76.771654,"[0.7604395604395604, 0.7785016286644951]","[0.7963176064441887, 0.7297709923664122]"

In [54]:
all_model_results["accuracy"] =all_model_results["accuracy"]/100
all_model_results

,accuracy,Precision,f1
Long Short-Term Memory,0.782152,"[0.7755555555555556, 0.7916666666666666]","[0.8078703703703703, 0.7484848484848485]"
Gated Recurent Unit,0.767717,"[0.7604395604395604, 0.7785016286644951]","[0.7963176064441887, 0.7297709923664122]"